server:
  port: 8086

spring:
  application:
    name: couponmoa-ai
  ai:
    vertex:
      ai:
        gemini:
          project-id: ${GOOGLE_CLOUD_PROJECT_ID}
          location: us-central1
          model: gemini-1.0-pro